services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: shorty
      POSTGRES_PASSWORD: shorty
      POSTGRES_DB: shorty
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
